version: '3'
services:
  dbcatalog:
    image: postgres:13  # Use uma imagem oficial do PostgreSQL
    environment:
      POSTGRES_DB: catalogdb  # Nome do banco de dados
      POSTGRES_USER: catalog  # Nome de usuário do banco de dados
      POSTGRES_PASSWORD: catalogpass  # Senha do banco de dados
    ports:
      - "5432:5432"  # Mapeie a porta do PostgreSQL do contêiner para a porta do host
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -p 5432 -U catalog -d catalogdb"]
      interval: 5s
      timeout: 5s
      retries: 5
  catalogapi:
    build:
      context: .
      dockerfile: Dockerfile  # Nome do seu Dockerfile de desenvolvimento
    ports:
      - "5001:5000"  # Mapeamento da porta do contêiner para a porta do host
    volumes:
      - .:/app  # Mapeamento do diretório local para o diretório de trabalho no contêiner
    environment:
      POSTGRES_DB: catalogdb  # Nome do banco de dados
      POSTGRES_USER: catalog  # Nome de usuário do banco de dados
      POSTGRES_PASSWORD: catalogpass  # Senha do banco de dados
      POSTGRES_SERVICE_HOST: dbcatalog  # Senha do banco de dados
      FLASK_ENV: development  # Configuração da variável de ambiente FLASK_ENV
    depends_on:
      dbcatalog:  # Aguarde o serviço do banco de dados PostgreSQL
        condition: service_healthy
