apiVersion: v1
kind: Service
metadata:
  name: catalog-svc
  labels:
    app: catalog-app
    service: catalog-app
spec:
  ports:
  - port: 5000
    name: http
  selector:
    app: catalog-app
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: delivery-catalog
  labels:
    account: catalog