apiVersion: v1
kind: Service
metadata:
  name: catalog-svc
  namespace: "default"
  labels:
    app: catalog-svc
spec:
  type: LoadBalancer
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: catalog-app
