apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-app
spec:
  selector:
    matchLabels:
      app: catalog-app
  replicas: 1
  template:
    metadata:
      labels:
        app: catalog-app
    spec:
      initContainers:
      - name: check-db-ready
        image: postgres:13-alpine
        command: ['sh', '-c', 
          'until pg_isready -h catalog-postgres-svc -p 5432; 
          do echo waiting for database; sleep 2; done;']
      containers:
      - name: catalog-app
        image: DOCKER_IMAGE
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
          - containerPort: 5000
        readinessProbe:
          httpGet:
            path: /ping
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 30
        livenessProbe:
          httpGet:
            path: /ping
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 60
        startupProbe:
          httpGet:
            path: /ping
            port: 5000
          failureThreshold: 3
          periodSeconds: 30
        env:
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: catalog-database-secret-config
                key: dbname
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: catalog-database-secret-config
                key: username
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: catalog-database-secret-config
                key: password
          - name: POSTGRES_SERVICE_HOST
            value: catalog-postgres-svc
          - name: TESTING
            value: "0"
