apiVersion: v1
kind: Service
metadata:
  name: catalogsvc
  namespace: "default"
  labels:
    app: catalogsvc
spec:
  type: LoadBalancer
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: catalogapp
